- name: "Copying Feroxbuster Config"
  copy:
    src: "{{ role_path }}/files/ferox-config.toml"
    dest: "/etc/feroxbuster"
  become: true
  become_method: sudo

- name: "Install Feroxbuster"
  shell: "curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh | bash -s $HOME/.local/bin"
  async: 45
  poll: 0
  become: true
  become_method: sudo