---
- name: "Installing tools from Gems"
  gem:
    name: "{{ item }}"
    state: latest
  loop:
    - builder
    - erubi
    - evil-winrm
    - gssapi
    - gyoku
    - httpclient
    - little-plugger
    - logger
    - logging
    - nori
    - rubyntlm
    - stringio
    - winrm
    - winrm-fs
  become: true
  become_method: sudo

