- name: "Download Nessus Install Package"
  shell: "wget https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.6.4-debian10_amd64.deb -O $HOME/Downloads/nessus.deb"
  become: true
  become_method: sudo

- name: "Install Nessus"
  shell: "dpkg -i $HOME/Downloads/nessus.deb"
  become: true
  become_method: sudo