---

- name: Configure ufw block
  become: yes
  block:
  - name: "Configure UFW"
    ufw:
      state: enabled
      policy: allow

  - name: "Log SYN packets in INPUT Chain"
    lineinfile:
      path: /etc/ufw/after.rules
      line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG] "'
      insertbefore: "# don't delete the 'COMMIT' line or these rules won't be processed"
    notify: "Restart ufw"
